  - pip:
      - absl-py
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - annotated-types
      - async-timeout
      - certifi
      - charset-normalizer
      - diso
      - einops
      - einops-exts
      - filelock
      - frozenlist
      - fsspec
      - gitdb
      - gitpython
      - grpcio
      - idna
      - ipywidgets
      - jupyterlab-widgets
      - lightning-utilities
      - markdown
      - markupsafe
      - mpmath
      - multidict
      - ninja
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-cufile-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-cusparselt-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - open3d
      - plyfile
      - propcache
      - protobuf
      - pydantic
      - pydantic-core
      - pytorch-lightning
      - pyyaml
      - rotary-embedding-torch
      - sentry-sdk
      - smmap
      - sympy
      - tensorboard
      - tensorboard-data-server
      - torch
      - torch-scatter
      - torchaudio
      - torchmetrics
      - torchvision
      - tqdm
      - trimesh
      - triton
      - typing-inspection
      - urllib3
      - wandb
      - widgetsnbextension
      - yarl
